import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NavigationBar from "./components/NavigationBar";
import { Toaster } from "sonner";
import Providers from "./components/Providers";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Providers>
          <div className="flex h-full w-full flex-col items-center justify-center">
            <NavigationBar />
            <div className="container h-full">{children}</div>
          </div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
