# download VSCode REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# Create a user
POST http://127.0.0.1:3001/api/users
content-type: application/json

{
  "username": "testuser",
  "email": "test@example.com"
}


###
# Create a Google Meet bot (deploy immediately) with default settings
POST http://127.0.0.1:3001/api/bots
content-type: application/json

{
  "userId": 5,
  "meetingTitle": "Test Google Meet",
  "meetingInfo": {
    "meetingUrl": "https://meet.google.com/orn-ovgv-dym",
    "platform": "google"
  }
}

###
# Create a Google Meet bot with custom settings (overriding some defaults)
POST http://127.0.0.1:3001/api/bots
content-type: application/json

{
  "userId": 1,
  "meetingTitle": "Test Google Meet with Custom Settings",
  "meetingInfo": {
    "meetingUrl": "https://meet.google.com/mvd-tibd-oxa",
    "platform": "google"
  },
  "botDisplayName": "Custom Bot Name",
  "automaticLeave": {
    "silenceDetection": {
      "timeout": 600000,
      "activateAfter": 120000
    },
    "waitingRoomTimeout": 180000
  }
}

###

# Create an API key
POST http://127.0.0.1:3001/api/api-keys
content-type: application/json

{
  "name": "Test API Key",
  "userId": 5
}


###

## Fake a backend callback to an example application
POST http://127.0.0.1:3002/api/callback
content-type: application/json

{
  "botId": 33
}


### 

# Get bots
GET http://127.0.0.1:3001/api/bots
content-type: application/json
x-api-key: 1724ec3e1d267d64289b6955cb972a7b99945ef72a9f33d934b762ac117a020b



### 

# Get Recording
GET http://127.0.0.1:3001/api/bots/23/recording
content-type: application/json
x-api-key: 1724ec3e1d267d64289b6955cb972a7b99945ef72a9f33d934b762ac117a020b
